#!/bin/bash
#SBATCH --job-name=ARGsOAP_wwOut_s2    # Name of your job
#SBATCH --account=def-mhoude           # ComputeCanada account
#SBATCH --time=48:00:00                
#SBATCH --mem=256G                     
#SBATCH --cpus-per-task=16             # More CPU threads
#SBATCH --output=logs/%x-%j.out
#SBATCH --error=logs/%x-%j.err
#SBATCH --mail-user=dliang53@XXXX.ca        # Replace with your actual email
#SBATCH --mail-type=ALL                    # Options: BEGIN, END, FAIL, ALL

# Load Python and virtual environment
module load python/3.11
source ~/envs/args_env/bin/activate

# Load necessary tools
module load diamond
module load bwa
module load samtools
module load blast+

# Ensure log and output directories exist
mkdir -p logs output_[Data_Name]

# Run ARGs-OAP Stage Two on Stage one files
args_oap stage_two \
  -i /home/dliang53/scratch/ECCC/output_[Data_Name] \ # Stage 1 files stored in output_[Data_Name]. 
  -o output_[Data_Name]\
  -t 16
