#!/bin/bash
#SBATCH --job-name=trimm_[FOLDER_NAME]
#SBATCH --account=def-mhoude           # ComputeCanada Account
#SBATCH --time=24:00:00                
#SBATCH --mem=200G                     
#SBATCH --cpus-per-task=16             # More CPU threads
#SBATCH --output=logs/%x-%j.out
#SBATCH --error=logs/%x-%j.err
#SBATCH --mail-user=dliang53@XXXX.ca        # Replace with your actual email
#SBATCH --mail-type=ALL                     # Options: BEGIN, END, FAIL, ALL

module load fastp 
for fq1 in /home/dliang53/scratch/ECCC/data/animals/*_1.fastq.gz; do
    sample=$(basename "$fq1" _1.fastq.gz)
    echo "Running fastp on $sample"

    fastp \
      -i "$fq1" \
      -o "/home/dliang53/scratch/ECCC/data/trimmed_animals3/${sample}_1.trimmed.fastq.gz" \
      --max_len1 100 \
      --thread 16 \

done

